name       : clisp
version    : '2.49'
release    : 2
homepage   : http://www.clisp.org/
source     :
    - https://mirrors.rit.edu/gnu/clisp/release/latest/clisp-2.49.tar.gz : bd2f6252c681337c0b6aa949fae3f92d3202dee3998c98a88ec28c72b115e866
license    : GPL-2.0-or-later
component  : programming.tools
summary    : CLISP is a high-level, general-purpose, object-oriented, dynamic, functional programming language.
builddeps  :
    - readline-devel
    - libiconv-devel
    - gcc
    - libffcall-devel
    - libsigsegv-devel
description: CLISP is a Common Lisp implementation by Bruno Haible, then of Karlsruhe University, and Michael Stoll, then of Munich University, both in Germany. It implements the language described in the ANSI Common Lisp standard with many extensions.
setup      : |
    ./configure CC='gcc -m64' --enable-shared --disable-static --with-readline --with-ffcall src
build      : |
    cd src
    %make -j1
install    : |
    cd src
    make DESTDIR=$installdir install
