name       : clisp
version    : 2.49
release    : 1
homepage   : http://www.clisp.org/
source     :
    - ftp://ftp.gnu.org/pub/gnu/clisp/release/2.49/clisp-2.49.tar.bz2 : 8132ff353afaa70e6b19367a25ae3d5a43627279c25647c220641fed00f8e890
license    : GPL-2.0
summary    : CLISP is a high-level, general-purpose, object-oriented, dynamic, functional programming language.
builddeps  :
    - readline-devel
    - libiconv-devel
    - gcc
    - libffcall-devel
    - libsigsegv-devel
description: |
    CLISP is a Common Lisp implementation by Bruno Haible, then of Karlsruhe University, and Michael Stoll, then of Munich University, both in Germany. 
    It implements the language described in the ANSI Common Lisp standard with many extensions.
setup      : |
    ./configure CC='gcc -m64' --enable-shared --disable-static --with-readline --with-ffcall src
build      : |
    cd src
    %make -j1
install    : |
    cd src
    make DESTDIR=$installdir install
